version: '3'

services:
  question-pro:
    image: 'question-pro:test'
    environment:
      - WORKDIR=/home/question-pro
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '80:80'